# Generated by Django 2.2.7 on 2019-11-14 10:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
