# Generated by Django 2.2.7 on 2019-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191114_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.TextField(),
        ),
    ]
